### PR TITLE
Fixed index.html not found error by changing index to html

### PR DESCRIPTION
**Pull request by josephworks**

### CODE REVIEW

**Comment by GMatrixGames** [comment]
Where is it now found? It loads fine if you set the DirectoryIndex as index.htm

**Comment by josephworks** [comment]
Not on my server
Go to http://josephworks.ddns.net/matrixdevteam.ml and click in home, you will get an error 404

**Comment by josephworks** [comment]
Plus, why is it htm and not html anyways...

**Comment by josephworks** [comment]
Plus, the default directory index it index.html, you wouldn’t need to change it if it was an html file

**Comment by josephworks** [comment]
https://www.quora.com/What-is-the-difference-between-a-html-and-a-htm-page for our purpose, html would be better

**Comment by GMatrixGames** [comment]
The reason why index.htm isn't working for you is because you're not using the .htaccess file that is provided, or you don't have AllowOverride enabled in you're apache2 config

**Pull request closed without merging**
